org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
neo_version=26.1.2.82
neo_version_range=[26.1.2.82,)
mod_id=simplebedrockmodel
mod_name=SimpleBedrockModel
mod_license=LGPL-3.0
mod_version=2.5.0-neoforge-mc26.1
mod_group_id=com.github.mcmodderanchor
mod_authors=[TartaricAcid, MaydayMemory, MoePus, Hidomatn, xjqsh]
mod_description=A library for loading Minecraft Bedrock Edition entity models and animation
